FROM sameli/manylinux2014_x86_64_cuda_12.3:latest

COPY . /workspace

WORKDIR /workspace

ENV TORCH_CUDA_ARCH_LIST="5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX"

RUN mkdir -p /output && \
    uv sync && uv run setup.py bdist_wheel --universal && \
    cp dist/*.whl /output

RUN rm -rf /workspace

WORKDIR /output
RUN ls -l /output